// <auto-generated />
using EFProjectionRepro;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFProjectionRepro.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("EFProjectionRepro.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("EFProjectionRepro.Entity", b =>
                {
                    b.OwnsMany("EFProjectionRepro.Child", "Children", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("EntityId", "Id");

                            b1.ToTable("Child");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");

                            b1.OwnsMany("EFProjectionRepro.Owned", "Owned", b2 =>
                                {
                                    b2.Property<int>("ChildEntityId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ChildId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("Value")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ChildEntityId", "ChildId", "Id");

                                    b2.ToTable("Owned");

                                    b2.WithOwner()
                                        .HasForeignKey("ChildEntityId", "ChildId");
                                });

                            b1.Navigation("Owned");
                        });

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
